apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.buyProcessor.name }}-service-account
  labels:
    helm.sh/chart: {{ include "market-provider-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    heritage: "{{ .Release.Service }}"
