apiVersion: rbac.authorization.k8s.io/v1
# This allows the buy-processor pod to create deployments & services in the service-composition namespace
kind: RoleBinding
metadata:
  name: {{ .Values.buyProcessor.name }}-depl-role-binding
  namespace: {{ .Values.buyProcessor.serviceCompositionNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.buyProcessor.name }}-service-account
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: deployment-service-creator
  apiGroup: rbac.authorization.k8s.io
