apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
  namespace: {{ .Values.buyProcessor.serviceCompositionNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}   