apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.offerDatabaseSecret.name }}
type: Opaque
data:
  {{ .Values.offerDatabaseSecret.secretUserKey }}: {{ .Values.offerDatabase.mongodbUsername | b64enc }}
  {{ .Values.offerDatabaseSecret.secretPasswordKey }}: {{ .Values.offerDatabase.mongodbPassword | b64enc }}
