apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.compositionqueue.secretName }}
  namespace: {{ .Values.buyProcessor.serviceCompositionNamespace }}
type: Opaque
data:
  username: {{ .Values.compositionqueue.rabbitmq.username | b64enc }}
  password: {{ .Values.credentials.rabbitmqPassword | b64enc }}
