apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.reputationDatabaseSecret.name }}
type: Opaque
data:
  {{ .Values.reputationDatabaseSecret.secretUserKey }}: {{ .Values.reputationDatabase.mongodbUsername | b64enc }}
  {{ .Values.reputationDatabaseSecret.secretPasswordKey }}: {{ .Values.reputationDatabase.mongodbPassword | b64enc }}
