apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.systemManager.name }}
  labels:
    helm.sh/chart: {{ include "market-provider-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    run: {{ .Values.systemManager.name }}
spec:
  type: {{ .Values.systemManager.service.type }}
  ports:
    - port: {{ .Values.systemManager.deployment.port }}
  {{- if .Values.systemManager.service.nodePort }}
      nodePort: {{ .Values.systemManager.service.nodePort }}
  {{- end }}
  selector:
    run: {{ .Values.systemManager.name }}