kind: PersistentVolume
apiVersion: v1
metadata:
  name: market-provider-rabbitmq
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/market-provider/rabbitmq"
    type: DirectoryOrCreate
