apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.sfbNexus.name }}
  namespace: {{ printf "%s%s" .Release.Namespace .Values.otfConfigurator.podNamespaceSuffix }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "sfb-imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.credentialSecretName }}
  namespace: {{ printf "%s%s" .Release.Namespace .Values.otfConfigurator.podNamespaceSuffix }}
type: Opaque
data:
  username: {{ .Values.credentials.userNexusUsername | b64enc}}   
  password: {{ .Values.credentials.userNexusPassword | b64enc}} 
  host: {{ template "docker-registry" . }}  