apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otfConfigurator.name }}
  labels:
    helm.sh/chart: {{ include "otf-provider-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    run: {{ .Values.otfConfigurator.name }}
spec:
  type: {{ .Values.otfConfigurator.service.type }}
  ports:
  {{- range .Values.otfConfigurator.deployment.ports }}
    - port: {{ .port }}
      nodePort: {{ .nodePort }}
      name: {{ .name }}
  {{- end }}
  selector:
    run: {{ .Values.otfConfigurator.name }}