apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.name }}
  labels:
    helm.sh/chart: {{ include "website-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    run: {{ .Values.website.name }}
spec:
  type: {{.Values.website.service.type }}
  ports:
    - port: {{ .Values.website.deployment.container.port }}
      nodePort: {{ .Values.website.service.nodePort }}
  selector:
    run: {{ .Values.website.name }}