apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.compositionqueue.secretName }}
type: Opaque
data:
  username: {{ .Values.compositionqueue.rabbitmq.username | b64enc }}
  password: {{ .Values.compositionqueue.rabbitmq.password | b64enc }}
