dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    alias: elasticsearch-master
    tags:
      - elasticsearch
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    alias: elasticsearch-data
    tags:
      - elasticsearch
  - name: kibana
    version: 7.17.3
    repository: https://helm.elastic.co
    alias: kibana

