# Default values for the execution part of the market-provider
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

credentials:
  name: user-nexus

masterNode:
  # If set to true the buy processor will read the nodes api and look for the hostname of the (tainted) master node
  autoConfig: true
  # if set to false, this value will be mounted into the buy-processor and used as the master nodes hostname (use this is cases where the master node is not tainted or the hostname not set)
  hostName:  "localhost"

config:
  marketProviderNamespace: market-provider

gateway:
  name: execution-gateway
  service:
    type: NodePort
  deployment:
    replicaCount: 1
    revisionHistoryLimit: 0
    container:
      image: aminfa/sede
      imagePullPolicy: Always
      tag: Gateway-latest
    ports:
    - name: gateway-rest
      port: 8080
      targetPort: 8080
      nodePort: 30370
    - name: gateway-telnet
      port: 2200
      targetPort: 2200
      nodePort: 30371

proxy:
  name: proxy
  service:
    type: NodePort
  deployment:
    replicaCount: 1
    revisionHistoryLimit: 0
    container:
      image: sede.proxy
      imagePullPolicy: Always
      tag: latest
    ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30380

kubernetesExecutorSpawner:
  masterNodeHostname: 
  name: kubernetes-executor-spawner
  executorNamespace: execution-executors
  service:
    type: NodePort
  deployment:
    replicaCount: 1
    revisionHistoryLimit: 0
    container:
      image: kubernetes_executor_spawner
      imagePullPolicy: Always
      tag: latest
    port: 8080
    nodePort: 31527

