apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
  namespace: {{ .Values.kubernetesExecutorSpawner.executorNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.sfbNexus.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "sfb-imagePullSecret" . }}   
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
type: Opaque
data:
  username:
    {{ .Values.credentials.userNexusUsername | b64enc }}
  password:
    {{ .Values.credentials.userNexusPassword | b64enc }}    
  host:
    {{ template "docker-registry" . }}
