apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubernetesExecutorSpawner.name }}
  labels:
    helm.sh/chart: {{ include "execution-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    run: {{ .Values.kubernetesExecutorSpawner.name }}
spec:
  type: {{ .Values.kubernetesExecutorSpawner.service.type }}
  ports:
    - port: {{ .Values.kubernetesExecutorSpawner.deployment.port }}
      nodePort: {{ .Values.kubernetesExecutorSpawner.deployment.nodePort }}
  selector:
    run: {{ .Values.kubernetesExecutorSpawner.name }}