apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: view-nodes-execution
rules:
- apiGroups: [""]
  # See the nodes public IP-Adress 
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "view"]
