kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.postgrest.name }}
  labels:
    app: {{ .Values.postgrest.name }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  PGRST_DB_URI: postgres://{{ .Values.postgres.database.adminName }}:{{ .Values.postgres.database.adminPassword }}@{{ .Values.postgres.name }}.{{ .Release.Namespace }}:{{ .Values.postgres.containerPort }}/{{ .Values.postgres.database.name }}
  PGRST_DB_SCHEMA: {{ .Values.postgres.database.schemaName }}
  PGRST_DB_ANON_ROLE: {{ .Values.postgres.database.anonRole }}
  PGRST_DB_POOL: "10"
#  PGRST_DB_EXTRA_SEARCH_PATH:

  PGRST_SERVER_HOST: "*4"
  PGRST_SERVER_PORT: "{{ .Values.postgrest.containerPort }}"

  PGRST_SERVER_PROXY_URI: http://{{ .Values.host }}:{{ .Values.postgrest.nodePort }}
#  PGRST_JWT_SECRET: foo
#  PGRST_SECRET_IS_BASE64: false
#  PGRST_JWT_AUD: your_audience_claim
#  PGRST_ROLE_CLAIM_KEY: .role

#  PGRST_MAX_ROWS: 1000
#  PGRST_PRE_REQUEST: stored_proc_name

