kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.swaggerui.name }}
  labels:
    app: {{ .Values.swaggerui.name }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  API_URL: http://{{ .Values.host }}:{{ .Values.postgrest.nodePort }}/

