kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.swaggerui.name }}
  labels:
    app: {{ .Values.swaggerui.name }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.swaggerui.name }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  type: NodePort
  ports:
  - port: {{ .Values.swaggerui.containerPort }}
    nodePort: {{ .Values.swaggerui.nodePort }}

